hw5:hw5table1 hw5table2 hw5table3
.PHONY : all
hw5table1:table1.cpp
	g++ table1.cpp -o table1
hw5table2:table2.cpp
	g++ table2.cpp -o table2
hw5table3:table3.cpp
	g++ table3.cpp -o table3
.PHONY:clean
clean:
	-$(RM) hw5table1 hw5table2 hw5table3
